{{- $token := get .Values "token" | default dict -}}
{{- $existingSecret := get $token "existingSecret" | default dict -}}
{{- $existingSecretName := get $existingSecret "name" | default "" -}}
{{- if not $existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k3s-server.fullname" . }}-token
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  annotations:
    {{- include "k3s-server.annotations" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token.value | quote }}
{{- end }}
