{{- if and (eq .Values.k3s.datastore.endpoint "") (not .Values.k3s.embeddedEtcd.enabled) }}
{{- fail "k3s.datastore.endpoint must be set when embedded etcd is disabled." }}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "k3s-server.fullname" . }}
  labels:
    {{- include "k3s-server.labels" . | nindent 4 }}
  annotations:
    {{- include "k3s-server.annotations" . | nindent 4 }}
spec:
  serviceName: {{ include "k3s-server.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k3s-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "k3s-server.labels" . | nindent 8 }}
      annotations:
        {{- include "k3s-server.annotations" . | nindent 8 }}
    spec:
      {{- if and .Values.antiAffinity.enabled (not .Values.affinity) }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "k3s-server.name" . }}
                  app.kubernetes.io/instance: {{ .Release.Name }}
              topologyKey: kubernetes.io/hostname
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if not .Values.persistence.enabled }}
      volumes:
        - name: k3s-data
          emptyDir: {}
      {{- end }}

      containers:
        - name: k3s
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            privileged: {{ .Values.securityContext.privileged }}

          {{- $existingSecret := default dict .Values.token.existingSecret }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K3S_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-token" (include "k3s-server.fullname" .)) $existingSecret.name }}
                  key: {{ default "token" $existingSecret.key }}
            {{- if not .Values.k3s.embeddedEtcd.enabled }}
            - name: K3S_DATASTORE_ENDPOINT
              value: {{ .Values.k3s.datastore.endpoint | quote }}
            {{- end }}
            - name: K3S_DATA_DIR
              value: /var/lib/rancher/k3s
            - name: K3S_LB_SERVER_PORT
              value: {{ .Values.k3s.lbServerPort | default 6444 | quote }}
            {{- if .Values.k3s.debug }}
            - name: K3S_DEBUG
              value: "true"
            {{- end }}
            {{- if and (not .Values.k3s.embeddedEtcd.enabled) .Values.k3s.datastore.cafile }}
            - name: K3S_DATASTORE_CAFILE
              value: {{ .Values.k3s.datastore.cafile | quote }}
            {{- end }}
            {{- if and (not .Values.k3s.embeddedEtcd.enabled) .Values.k3s.datastore.certfile }}
            - name: K3S_DATASTORE_CERTFILE
              value: {{ .Values.k3s.datastore.certfile | quote }}
            {{- end }}
            {{- if and (not .Values.k3s.embeddedEtcd.enabled) .Values.k3s.datastore.keyfile }}
            - name: K3S_DATASTORE_KEYFILE
              value: {{ .Values.k3s.datastore.keyfile | quote }}
            {{- end }}
          command:
            - /bin/sh
            - -c
            - |
              set -euo pipefail

              EXTRA_ARGS=""
              {{- range .Values.k3s.extraArgs }}
              EXTRA_ARGS="$EXTRA_ARGS {{ . }}"
              {{- end }}

              {{- if not .Values.k3s.debug }}
              unset K3S_DEBUG
              {{- end }}

              TLS_SANS=""
              {{- range .Values.k3s.tlsSANs }}
              TLS_SANS="$TLS_SANS --tls-san {{ . }}"
              {{- end }}

              SERVER_ARGS=""
              {{- if .Values.k3s.embeddedEtcd.enabled }}
              ORDINAL="${POD_NAME##*-}"
              if [ "$ORDINAL" -eq 0 ]; then
                echo "Initializing embedded etcd cluster"
                SERVER_ARGS="--cluster-init"
              else
                echo "Joining embedded etcd cluster via headless DNS"
                SERVER_ARGS="--server https://{{ include "k3s-server.fullname" . }}-0.{{ include "k3s-server.fullname" . }}:{{ .Values.k3s.apiPort }}"
              fi
              {{- end }}

              echo "Starting k3s server"
              exec k3s server \
                --https-listen-port {{ .Values.k3s.apiPort }} \
                $TLS_SANS \
                $SERVER_ARGS \
                $EXTRA_ARGS

          ports:
            - name: https
              containerPort: {{ .Values.k3s.apiPort }}
              protocol: TCP
            {{- if .Values.k3s.embeddedEtcd.enabled }}
            - name: etcd-client
              containerPort: 2379
              protocol: TCP
            - name: etcd-peer
              containerPort: 2380
              protocol: TCP
            - name: etcd-metrics
              containerPort: 2381
              protocol: TCP
            {{- end }}

          {{- if .Values.healthChecks.enabled }}
          livenessProbe:
            tcpSocket:
              port: https
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthChecks.liveness.failureThreshold }}
            successThreshold: {{ .Values.healthChecks.liveness.successThreshold }}

          readinessProbe:
            tcpSocket:
              port: https
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.healthChecks.readiness.failureThreshold }}
            successThreshold: {{ .Values.healthChecks.readiness.successThreshold }}

          {{- if .Values.healthChecks.startup.enabled }}
          startupProbe:
            tcpSocket:
              port: https
            periodSeconds: {{ .Values.healthChecks.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.healthChecks.startup.failureThreshold }}
          {{- end }}
          {{- end }}

          volumeMounts:
            - name: k3s-data
              mountPath: /var/lib/rancher/k3s

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: k3s-data
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
        {{- end }}
  {{- end }}
